### ISSUE TITLE
Crashes on first lunch if Google Analytics Custom Metrics are empty.

### ISSUE THREAD

**Issue by andresbrun** [segmentio/analytics-ios#473]
For Google analytics integration in advance options there is the possibility of adding Custom Metrics. But at least this is always one (even if it is empty). That makes the app crash in  SEGGoogleAnalyticsIntegration.m:230 because "null" doesn't have the 5th character where the method is looking for a number.

**Comment by f2prateek** [comment]
Thanks, should be fixed by https://github.com/segment-integrations/analytics-ios-integration-google-analytics/commit/b6ed19805a0d32b314ea20c25de2330dab8d8582.

**Comment by andresbrun** [comment]
Code is definitely better by removing those magic numbers but this doesn't solve the issue. I created a PR for this:
https://github.com/segment-integrations/analytics-ios-integration-google-analytics/pull/1
