### ISSUE TITLE
NSAssert: Key `url` is a NSURL and can't be serialized for delivery

### ISSUE THREAD

**Issue by krin-san** [segmentio/analytics-ios#947]
Segment cannot handle app start options dictionary on iOS 14 when it contains deeplink url (when application was started to handle that deep link).

Related to #937 and #936
Affected version: [v4.0.5](https://github.com/segmentio/analytics-ios/releases/tag/4.0.5) and 7a8387b1048915b22bbc971ff308baa6a0e7e13a (latest master at the moment of testing).
iOS version: 14.0.1
IDE: Xcode 12.0.1

Issues:
- Assertion in `-[NSDictionary(SerializableDeepCopy) serializableDeepCopy:]` on DEBUG builds
- Missing tracking data (deep link) on other builds

Reasons:
- `NSURL` is not mentioned in https://github.com/segmentio/analytics-ios/blob/7a8387b1048915b22bbc971ff308baa6a0e7e13a/Segment/Internal/SEGUtils.m#L507
- `NSURL` don't conform to `SEGSerializable`

<img width="537" alt="Screenshot 2020-10-08 at 09 30 27" src="https://user-images.githubusercontent.com/2318002/95430602-471a4300-094c-11eb-9fb0-1c4de8eb136b.png">

LLDB log at selected stack trace point:
```
po note.userInfo
{
    UIApplicationLaunchOptionsURLKey = "my_app://deeplink";
}

po [note.userInfo[@"UIApplicationLaunchOptionsURLKey"] class]
NSURL
```

**Comment by krin-san** [comment]
Adding `[obj isKindOfClass:[NSURL class]] ||` to the list of serializable classes seem to fix this issue.

**Comment by dannyhertz** [comment]
Im running into this issue as well. Were you able to patch it locally @krin-san or did you have to fork the library and fix it yourself?

**Comment by krin-san** [comment]
@dannyhertz I patched SEGUtils.m in place, right in Pods folder to see if that's enough. On Monday I can prepare a PR if no one wants to make that earlier.

**Comment by krin-san** [comment]
@dannyhertz it took some time to prioritize and test that, but PR is ready.
Could you check if that fixes your issue too? To install the fork change your Podfile like that:
```diff
- pod 'Analytics'
+ pod 'Analytics', :git => 'https://github.com/krin-san/analytics-ios.git', :branch => 'bugfix/launch_with_deeplink'
```

**Comment by migs647** [comment]
we're looking at this today

**Comment by sanhue0302** [comment]
I think this is same problem as #959 ?

**Comment by darrenspriet** [comment]
Any idea when this fix is going in?

**Comment by bsneed** [comment]
Should have this resolved tomorrow.  #959 shed a little more light on the issue.

**Comment by bsneed** [comment]
Oops, closed by mistake.  Meant to hit the comment button.

**Comment by darrenspriet** [comment]
Issue I am having is opening a URL from a widget in the non-running state.  I get the crashed described above. And adding this line actually fixes it `[obj isKindOfClass:[NSURL class]] |` as described.  Is this fix or another fix resolving this issue in a release available?

**Comment by sanhue0302** [comment]
Doesn't  NSURL confirms to SEGSerializable?
 There is a category in [SEGAnalyticsUtils.m](7a8387b1048915b22bbc971ff308baa6a0e7e13a/Segment/Classes/SEGAnalyticsUtils.m)

I think It should return YES in SEGUtil.m:509

**Comment by darrenspriet** [comment]
Awesome, I see the change in 4.1.0.  I was trying to find which release the change went into.  Thank you for clarifying!

**Comment by bsneed** [comment]
Fixed!  Will be on `master` to try out shortly.  Release coming soon.

**Comment by bstillitano** [comment]
This is still happening with iOS 16 using analytics-ios 4.1.6
